// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIB64dWxzuSW_r9rpDSYJpfqpjK5X2eNM',
    appId: '1:878194092081:web:eabb6c9bd8bbd2eb484d10',
    messagingSenderId: '878194092081',
    projectId: 'study-flutter-08-cchef05-59941',
    authDomain: 'study-flutter-08-cchef05-59941.firebaseapp.com',
    storageBucket: 'study-flutter-08-cchef05-59941.appspot.com',
    measurementId: 'G-VT27JNN3H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-8zT3mSAB9vSf2Rlj1p1QTszMXVb4UE',
    appId: '1:878194092081:android:05f76f467d6cb25a484d10',
    messagingSenderId: '878194092081',
    projectId: 'study-flutter-08-cchef05-59941',
    storageBucket: 'study-flutter-08-cchef05-59941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYE8KvsPw1q94fpMmpUuxSPDdrfXUSv-E',
    appId: '1:878194092081:ios:1f7e34f1a2a2749f484d10',
    messagingSenderId: '878194092081',
    projectId: 'study-flutter-08-cchef05-59941',
    storageBucket: 'study-flutter-08-cchef05-59941.appspot.com',
    iosClientId: '878194092081-4jpbku4c44nk326f39en9gkshi69pd58.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFlutter08Codingchef05Chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYE8KvsPw1q94fpMmpUuxSPDdrfXUSv-E',
    appId: '1:878194092081:ios:1f7e34f1a2a2749f484d10',
    messagingSenderId: '878194092081',
    projectId: 'study-flutter-08-cchef05-59941',
    storageBucket: 'study-flutter-08-cchef05-59941.appspot.com',
    iosClientId: '878194092081-4jpbku4c44nk326f39en9gkshi69pd58.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFlutter08Codingchef05Chat',
  );
}
